theirs:
	cat theirs.txt | cargo run --bin part_one

theirs2:
	cat theirs.txt | cargo run --bin part_two

mine:
	cat mine.txt | cargo run --bin part_one

mine2:
	cat mine.txt | cargo run --bin part_two

