theirs:
	watch -n 1 "cat theirs.txt | cargo run --bin part_one"

theirs2:
	watch -n 1 "cat theirs.txt | cargo run --bin part_two"

mine:
	watch -n 1 "cat mine.txt | cargo run --bin part_one"

mine2:
	watch -n 1 "cat mine.txt | cargo run --bin part_two"
